// The "Try a sample sketch" pool. Files live in public/samples/ and are
// generated by scripts/make-samples.mjs (run once; regenerate after edits).
// The uploader picks one at random per visit and previews it in the dropzone.
export type SampleSketch = { file: string; label: string };

export const SAMPLE_SKETCHES: readonly SampleSketch[] = [
  { file: 'sample-01-saas.png', label: 'SaaS landing page' },
  { file: 'sample-02-portfolio.png', label: 'portfolio gallery' },
  { file: 'sample-03-restaurant.png', label: 'restaurant page' },
  { file: 'sample-04-pricing.png', label: 'pricing page' },
  { file: 'sample-05-blog.png', label: 'blog index' },
  { file: 'sample-06-contact.png', label: 'contact page' },
  { file: 'sample-07-testimonials.png', label: 'agency testimonials' },
  { file: 'sample-08-startup.png', label: 'startup landing' },
  { file: 'sample-09-travel.png', label: 'travel gallery' },
  { file: 'sample-10-conference.png', label: 'conference site' },
  { file: 'sample-11-store.png', label: 'online store' },
  { file: 'sample-12-gym.png', label: 'gym landing page' },
];
